//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stahovanie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dlznici_Entities : DbContext
    {
        public Dlznici_Entities()
            : base("name=Dlznici_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Danovy_Urad> Danovy_Urad { get; set; }
        public virtual DbSet<Socialna_Poistovna> Socialna_Poistovna { get; set; }
        public virtual DbSet<VsZP_Samoplatitelia> VsZP_Samoplatitelia { get; set; }
        public virtual DbSet<VsZP_Zamestnavatelia> VsZP_Zamestnavatelia { get; set; }
        public virtual DbSet<Zp_Union> Zp_Union { get; set; }
        public virtual DbSet<KurzovyListok> KurzovyListok { get; set; }
    }
}
